version: "3.8"  # Update to version 3.8 for compatibility (since version is deprecated)

services:
  web:
    image: nginx:latest
    volumes:
      - ./src:/usr/share/nginx/html
    ports:
      - "80:80"
